// ─── Skill System Data Layer ───────────────────────────────────────────────

export type SkillCategory = "Frontend" | "Backend" | "Mobile" | "AI" | "Design" | "Database" | "Security" | "DevOps" | "Testing" | "Performance" | "Accessibility" | "Cloud" | "Automation" | "Integrations" | "Documentation"

export type SkillHealth = "healthy" | "degraded" | "unavailable"
export type SkillAuthor = "SHANGO" | "Community" | "Verified"

export interface SkillUpdateEntry {
  version: string
  date: string
  note: string
}

export interface Skill {
  id: string
  name: string
  monogram: string // 2-char abbreviation for the icon
  purpose: string // One-liner: what SHANGO gains
  description: string // 2-3 sentences explaining the skill
  capabilities: string[] // Bullet list of what it enables
  languages: string[] // Programming languages
  frameworks: string[] // Frameworks / libraries
  requiredConnectors: string[]
  recommendedSkills: string[] // IDs of recommended companion skills
  version: string
  author: SkillAuthor
  category: SkillCategory
  featured: boolean
  tags: string[]
  permissions: string[]
  usageCount: number // catalog metadata, intentionally not presented as a live metric
  health: SkillHealth
  updateHistory: SkillUpdateEntry[]
  hasUpdate?: boolean
  updateVersion?: string
  documentation?: string // extended markdown-style prose for the docs section
}

export const ALL_SKILLS: Skill[] = [
  // ── Frontend ──────────────────────────────────────────────────────────────
  {
    id: "react",
    name: "React",
    monogram: "Re",
    purpose: "Build composable UIs with hooks and concurrent rendering",
    description:
      "Teaches SHANGO to generate idiomatic React components, hooks, context, and performance patterns. Covers React 18/19 concurrent features, Suspense, and the App Router paradigm.",
    capabilities: [
      "Functional components and hooks",
      "Context and state management",
      "Concurrent rendering and Suspense",
      "Custom hooks and composition",
      "Server components (RSC)",
      "React DevTools integration",
    ],
    languages: ["TypeScript", "JavaScript"],
    frameworks: ["React", "React DOM", "React Native"],
    requiredConnectors: [],
    recommendedSkills: ["typescript", "tailwind", "nextjs"],
    version: "2.4.1",
    author: "SHANGO",
    category: "Frontend",
    featured: true,
    tags: ["ui", "components", "hooks", "jsx"],
    permissions: ["Read project structure", "Generate component files"],
    usageCount: 14820,
    health: "healthy",
    hasUpdate: false,
    documentation:
      "When React is active, SHANGO defaults to functional components with hooks. State is managed via useState and useReducer; side effects via useEffect. Context is used sparingly — co-located state is preferred. Custom hooks are extracted whenever logic is reused across two or more components. Server components are generated when the target framework supports them (Next.js App Router). The skill covers React 18 and 19, including concurrent features, Suspense boundaries, and the transition API.",
    updateHistory: [
      {
        version: "2.4.1",
        date: "2026-07-01",
        note: "React 19 hooks support added",
      },
      {
        version: "2.3.0",
        date: "2026-04-12",
        note: "Server components pattern library",
      },
      {
        version: "2.2.0",
        date: "2026-01-08",
        note: "Concurrent features coverage",
      },
    ],
  },
  {
    id: "typescript",
    name: "TypeScript",
    monogram: "Ts",
    purpose: "Generate fully typed, production-safe code at every layer",
    description:
      "Enables SHANGO to write strict TypeScript throughout — inferred types, generics, discriminated unions, and utility types. Every generated interface, function, and API call is type-safe.",
    capabilities: [
      "Strict type inference",
      "Generic patterns and utility types",
      "Discriminated unions",
      "Declaration merging",
      "Type narrowing",
      "Path aliases",
    ],
    languages: ["TypeScript"],
    frameworks: ["ts-node", "tsc", "tsx"],
    requiredConnectors: [],
    recommendedSkills: ["react", "nodejs"],
    version: "3.1.0",
    author: "SHANGO",
    category: "Frontend",
    featured: true,
    tags: ["types", "safety", "dx"],
    permissions: ["Read project structure", "Generate type definitions"],
    usageCount: 18240,
    health: "healthy",
    hasUpdate: false,
    documentation:
      "With TypeScript active, SHANGO enables strict mode by default (noImplicitAny, strictNullChecks, exactOptionalPropertyTypes). All generated functions include explicit return types. API responses are typed via interface declarations, never inline. Generics are used for reusable utilities; discriminated unions model state machines. Utility types (Partial, Required, Pick, Omit, ReturnType) are applied where they reduce redundancy without obscuring intent.",
    updateHistory: [
      {
        version: "3.1.0",
        date: "2026-06-15",
        note: "TypeScript 5.5 pattern support",
      },
      { version: "3.0.0", date: "2026-02-20", note: "Full generics overhaul" },
    ],
  },
  {
    id: "tailwind",
    name: "Tailwind CSS",
    monogram: "Tw",
    purpose: "Design-system-first utility styling without leaving JSX",
    description:
      "SHANGO generates Tailwind v4 utility classes with token-aware spacing, color, and typography. Includes responsive breakpoints, dark mode, and component extraction patterns.",
    capabilities: [
      "Utility class generation",
      "Responsive design patterns",
      "Dark mode implementation",
      "Custom plugin authoring",
      "CSS variable theming (v4)",
      "JIT compilation patterns",
    ],
    languages: ["CSS", "TypeScript", "JavaScript"],
    frameworks: ["Tailwind CSS v4", "PostCSS"],
    requiredConnectors: [],
    recommendedSkills: ["react", "nextjs"],
    version: "1.8.2",
    author: "SHANGO",
    category: "Frontend",
    featured: true,
    tags: ["css", "design", "utility", "styling"],
    permissions: ["Read project structure", "Modify CSS files"],
    usageCount: 12300,
    health: "healthy",
    hasUpdate: true,
    updateVersion: "1.9.0",
    updateHistory: [
      {
        version: "1.8.2",
        date: "2026-06-28",
        note: "Tailwind v4 theme block support",
      },
      {
        version: "1.7.0",
        date: "2026-03-10",
        note: "CSS variable design tokens",
      },
    ],
  },
  {
    id: "nextjs",
    name: "Next.js",
    monogram: "Nx",
    purpose: "Full-stack React with file-system routing and edge deployment",
    description:
      "SHANGO builds Next.js applications with App Router, Server Components, API routes, and optimised image handling. Covers middleware, caching strategies, and ISR patterns.",
    capabilities: [
      "App Router and layouts",
      "Server and client components",
      "API routes and middleware",
      "Static and incremental generation",
      "Image and font optimisation",
      "Edge runtime support",
    ],
    languages: ["TypeScript", "JavaScript"],
    frameworks: ["Next.js", "React", "Vercel"],
    requiredConnectors: [],
    recommendedSkills: ["react", "typescript", "tailwind"],
    version: "2.2.0",
    author: "SHANGO",
    category: "Frontend",
    featured: false,
    tags: ["fullstack", "ssr", "routing", "vercel"],
    permissions: [
      "Read project structure",
      "Generate page files",
      "Modify next.config.ts",
    ],
    usageCount: 9870,
    health: "healthy",
    hasUpdate: false,
    updateHistory: [
      {
        version: "2.2.0",
        date: "2026-05-20",
        note: "Partial prerendering support",
      },
      { version: "2.1.0", date: "2026-02-08", note: "Server actions coverage" },
    ],
  },
  {
    id: "vue",
    name: "Vue",
    monogram: "Vu",
    purpose: "Progressive UI framework with composition API",
    description:
      "Enables SHANGO to generate Vue 3 components using the Composition API, Pinia state management, and Vue Router. Covers reactivity primitives, composables, and script setup syntax.",
    capabilities: [
      "Composition API and script setup",
      "Pinia state management",
      "Vue Router patterns",
      "Reactivity system deep dives",
      "Custom composables",
    ],
    languages: ["TypeScript", "JavaScript"],
    frameworks: ["Vue 3", "Nuxt 3", "Pinia", "Vue Router"],
    requiredConnectors: [],
    recommendedSkills: ["typescript", "tailwind"],
    version: "1.5.0",
    author: "Community",
    category: "Frontend",
    featured: false,
    tags: ["ui", "spa", "composition"],
    permissions: ["Read project structure", "Generate .vue files"],
    usageCount: 4210,
    health: "healthy",
    hasUpdate: false,
    updateHistory: [
      { version: "1.5.0", date: "2026-04-14", note: "Nuxt 4 support" },
    ],
  },
  // ── Backend ───────────────────────────────────────────────────────────────
  {
    id: "nodejs",
    name: "Node.js",
    monogram: "No",
    purpose: "Server-side JavaScript with modern async patterns",
    description:
      "SHANGO generates Node.js services with async/await, streams, cluster, and worker threads. Covers REST API design, middleware composition, and production deployment patterns.",
    capabilities: [
      "REST API scaffolding",
      "Async/await patterns",
      "Stream processing",
      "Middleware composition",
      "Error handling strategies",
      "Production clustering",
    ],
    languages: ["TypeScript", "JavaScript"],
    frameworks: ["Express", "Fastify", "Hono", "Koa"],
    requiredConnectors: [],
    recommendedSkills: ["typescript", "database-postgres"],
    version: "2.6.0",
    author: "SHANGO",
    category: "Backend",
    featured: true,
    tags: ["server", "api", "rest", "async"],
    permissions: [
      "Read project structure",
      "Generate server files",
      "Read environment variables",
    ],
    usageCount: 11430,
    health: "healthy",
    hasUpdate: false,
    updateHistory: [
      {
        version: "2.6.0",
        date: "2026-06-01",
        note: "Node 22 native fetch and streams",
      },
      { version: "2.5.0", date: "2026-03-15", note: "Hono framework support" },
    ],
  },
  {
    id: "python",
    name: "Python",
    monogram: "Py",
    purpose: "Rapid backend development with Python's rich ecosystem",
    description:
      "Enables SHANGO to write idiomatic Python — FastAPI services, data processing pipelines, async handlers, and Pydantic models. Covers modern Python 3.12+ features.",
    capabilities: [
      "FastAPI and async handlers",
      "Pydantic data models",
      "Async database access",
      "Data processing pipelines",
      "Type hints and protocols",
      "Packaging and dependencies",
    ],
    languages: ["Python"],
    frameworks: ["FastAPI", "Django", "Flask", "Pydantic"],
    requiredConnectors: [],
    recommendedSkills: ["ai-rag", "database-postgres"],
    version: "1.9.0",
    author: "SHANGO",
    category: "Backend",
    featured: false,
    tags: ["api", "data", "scripting"],
    permissions: ["Read project structure", "Generate .py files"],
    usageCount: 8760,
    health: "healthy",
    hasUpdate: true,
    updateVersion: "2.0.0",
    updateHistory: [
      {
        version: "1.9.0",
        date: "2026-05-10",
        note: "Python 3.12 pattern matching",
      },
      {
        version: "1.8.0",
        date: "2026-01-20",
        note: "FastAPI lifespan patterns",
      },
    ],
  },
  {
    id: "go",
    name: "Go",
    monogram: "Go",
    purpose: "High-performance concurrent services in Go",
    description:
      "SHANGO generates idiomatic Go — goroutines, channels, interfaces, and error handling. Covers HTTP services with the standard library, database access, and deployment to cloud runtimes.",
    capabilities: [
      "Goroutine concurrency patterns",
      "Channel communication",
      "Interface composition",
      "HTTP service scaffolding",
      "Error wrapping conventions",
      "Module and workspace management",
    ],
    languages: ["Go"],
    frameworks: ["net/http", "Gin", "Echo", "GORM"],
    requiredConnectors: [],
    recommendedSkills: ["cloud-aws", "database-postgres"],
    version: "1.4.0",
    author: "Community",
    category: "Backend",
    featured: false,
    tags: ["performance", "concurrency", "api"],
    permissions: ["Read project structure", "Generate .go files"],
    usageCount: 3140,
    health: "healthy",
    hasUpdate: false,
    updateHistory: [
      {
        version: "1.4.0",
        date: "2026-04-05",
        note: "Go 1.23 ranging patterns",
      },
    ],
  },
  {
    id: "rust",
    name: "Rust",
    monogram: "Rs",
    purpose: "Memory-safe systems programming and WebAssembly",
    description:
      "Enables SHANGO to write safe, performant Rust — ownership patterns, lifetimes, async with Tokio, and WASM compilation targets. Covers Axum web services and Serde serialisation.",
    capabilities: [
      "Ownership and borrowing patterns",
      "Async with Tokio",
      "Axum web services",
      "WASM compilation targets",
      "Serde serialisation",
      "Error handling with anyhow/thiserror",
    ],
    languages: ["Rust"],
    frameworks: ["Axum", "Tokio", "Serde", "wasm-bindgen"],
    requiredConnectors: [],
    recommendedSkills: ["wasm", "performance"],
    version: "1.2.0",
    author: "Community",
    category: "Backend",
    featured: false,
    tags: ["systems", "wasm", "memory-safe"],
    permissions: ["Read project structure", "Generate .rs files"],
    usageCount: 1820,
    health: "healthy",
    hasUpdate: false,
    updateHistory: [
      {
        version: "1.2.0",
        date: "2026-03-22",
        note: "Axum 0.8 and RAII patterns",
      },
    ],
  },
  // ── Mobile ────────────────────────────────────────────────────────────────
  {
    id: "react-native",
    name: "React Native",
    monogram: "RN",
    purpose: "Cross-platform mobile apps with a shared React codebase",
    description:
      "SHANGO builds React Native applications with the New Architecture (Fabric + JSI), Expo SDK, and native module bridging. Covers navigation, animations, and platform-specific code.",
    capabilities: [
      "Expo SDK and managed workflow",
      "React Navigation patterns",
      "Reanimated and Gesture Handler",
      "Native module bridging",
      "Platform-specific code splitting",
      "OTA updates with EAS",
    ],
    languages: ["TypeScript", "JavaScript"],
    frameworks: ["React Native", "Expo", "React Navigation", "Reanimated"],
    requiredConnectors: [],
    recommendedSkills: ["react", "typescript"],
    version: "2.1.0",
    author: "SHANGO",
    category: "Mobile",
    featured: true,
    tags: ["ios", "android", "cross-platform", "expo"],
    permissions: ["Read project structure", "Generate screen files"],
    usageCount: 5630,
    health: "healthy",
    hasUpdate: false,
    updateHistory: [
      {
        version: "2.1.0",
        date: "2026-05-30",
        note: "New Architecture full support",
      },
      {
        version: "2.0.0",
        date: "2026-01-15",
        note: "Expo Router v4 integration",
      },
    ],
  },
  {
    id: "swift",
    name: "Swift",
    monogram: "Sw",
    purpose: "Native iOS and macOS applications with SwiftUI",
    description:
      "Enables SHANGO to write modern Swift — SwiftUI views, Combine publishers, Swift concurrency (async/await, actors), and Core Data integration. Covers App Store distribution patterns.",
    capabilities: [
      "SwiftUI view composition",
      "Swift concurrency (actors, async/await)",
      "Combine reactive patterns",
      "Core Data integration",
      "WidgetKit extensions",
      "App Store submission",
    ],
    languages: ["Swift"],
    frameworks: ["SwiftUI", "Combine", "Core Data", "UIKit"],
    requiredConnectors: [],
    recommendedSkills: ["cloud-aws"],
    version: "1.6.0",
    author: "Community",
    category: "Mobile",
    featured: false,
    tags: ["ios", "macos", "native", "apple"],
    permissions: ["Read project structure", "Generate .swift files"],
    usageCount: 2940,
    health: "healthy",
    hasUpdate: false,
    updateHistory: [
      {
        version: "1.6.0",
        date: "2026-06-10",
        note: "Swift 6 concurrency model",
      },
    ],
  },
  // ── AI ────────────────────────────────────────────────────────────────────
  {
    id: "ai-rag",
    name: "RAG",
    monogram: "RA",
    purpose: "Retrieval-augmented generation with vector search",
    description:
      "SHANGO designs complete RAG pipelines — document ingestion, chunking strategies, embedding generation, vector store integration, and retrieval-augmented prompting. Covers hallucination mitigation techniques.",
    capabilities: [
      "Document chunking strategies",
      "Embedding generation pipelines",
      "Vector store integration",
      "Retrieval prompt engineering",
      "Re-ranking and filtering",
      "Hallucination mitigation",
    ],
    languages: ["Python", "TypeScript"],
    frameworks: ["LangChain", "LlamaIndex", "Pinecone", "pgvector"],
    requiredConnectors: ["OpenAI", "Anthropic"],
    recommendedSkills: ["python", "database-postgres", "ai-agents"],
    version: "1.8.0",
    author: "SHANGO",
    category: "AI",
    featured: true,
    tags: ["llm", "embeddings", "search", "vector"],
    permissions: [
      "Read project files",
      "Access connected AI APIs",
      "Read vector store config",
    ],
    usageCount: 7840,
    health: "healthy",
    hasUpdate: true,
    updateVersion: "2.0.0",
    updateHistory: [
      {
        version: "1.8.0",
        date: "2026-06-20",
        note: "Multi-vector retrieval strategies",
      },
      { version: "1.7.0", date: "2026-04-05", note: "Hybrid search with BM25" },
      { version: "1.6.0", date: "2026-01-28", note: "pgvector integration" },
    ],
  },
  {
    id: "ai-agents",
    name: "Agents",
    monogram: "Ag",
    purpose: "Design autonomous agents with tool use and memory",
    description:
      "Teaches SHANGO to architect agentic systems — tool definitions, memory backends, multi-agent orchestration, and human-in-the-loop patterns. Covers Claude's extended thinking and tool use APIs.",
    capabilities: [
      "Tool definition and routing",
      "Short-term and long-term memory",
      "Multi-agent orchestration",
      "Human-in-the-loop patterns",
      "Extended thinking",
      "Agent evaluation and tracing",
    ],
    languages: ["Python", "TypeScript"],
    frameworks: ["Anthropic SDK", "LangGraph", "CrewAI", "AutoGen"],
    requiredConnectors: ["Anthropic"],
    recommendedSkills: ["ai-rag", "python"],
    version: "1.4.0",
    author: "SHANGO",
    category: "AI",
    featured: true,
    tags: ["agents", "tool-use", "orchestration", "llm"],
    permissions: [
      "Read project files",
      "Access connected AI APIs",
      "Write memory files",
    ],
    usageCount: 6120,
    health: "healthy",
    hasUpdate: false,
    updateHistory: [
      {
        version: "1.4.0",
        date: "2026-07-02",
        note: "Claude 4 extended thinking support",
      },
      { version: "1.3.0", date: "2026-04-18", note: "LangGraph integration" },
    ],
  },
  {
    id: "ai-mcp",
    name: "MCP",
    monogram: "MC",
    purpose: "Model Context Protocol servers and clients",
    description:
      "SHANGO designs and implements MCP servers — tool definitions, resource handlers, prompt templates, and sampling endpoints. Covers both STDIO and SSE transport layers.",
    capabilities: [
      "MCP server scaffolding",
      "Tool and resource definitions",
      "Prompt template design",
      "STDIO and SSE transports",
      "Client-side MCP integration",
      "Authentication and security",
    ],
    languages: ["TypeScript", "Python"],
    frameworks: ["MCP SDK", "FastMCP", "Claude Desktop"],
    requiredConnectors: ["Anthropic"],
    recommendedSkills: ["typescript", "ai-agents"],
    version: "1.1.0",
    author: "SHANGO",
    category: "AI",
    featured: false,
    tags: ["mcp", "protocol", "tools", "anthropic"],
    permissions: ["Read project structure", "Generate MCP config files"],
    usageCount: 2890,
    health: "healthy",
    hasUpdate: false,
    updateHistory: [
      {
        version: "1.1.0",
        date: "2026-06-25",
        note: "OAuth 2.1 MCP auth support",
      },
    ],
  },
  // ── Design ────────────────────────────────────────────────────────────────
  {
    id: "design-system",
    name: "Design Systems",
    monogram: "DS",
    purpose: "Token-based design systems with systematic component APIs",
    description:
      "SHANGO builds design systems from the ground up — design tokens, semantic colour scales, typography ramps, spacing primitives, and component APIs with full accessibility. Covers Storybook documentation.",
    capabilities: [
      "Design token architecture",
      "Semantic colour scales",
      "Typography and spacing systems",
      "Component API design",
      "Storybook integration",
      "Theme switching and dark mode",
    ],
    languages: ["TypeScript", "CSS"],
    frameworks: ["Storybook", "Style Dictionary", "Radix UI"],
    requiredConnectors: [],
    recommendedSkills: ["react", "tailwind", "accessibility"],
    version: "2.0.0",
    author: "SHANGO",
    category: "Design",
    featured: true,
    tags: ["tokens", "components", "storybook", "theming"],
    permissions: [
      "Read project structure",
      "Generate token files",
      "Modify CSS variables",
    ],
    usageCount: 5420,
    health: "healthy",
    hasUpdate: false,
    updateHistory: [
      {
        version: "2.0.0",
        date: "2026-05-05",
        note: "CSS @property token definitions",
      },
      {
        version: "1.9.0",
        date: "2026-02-14",
        note: "Figma token sync support",
      },
    ],
  },
  {
    id: "motion",
    name: "Motion",
    monogram: "Mo",
    purpose: "Intentional animation with restrained motion design",
    description:
      "Teaches SHANGO to design purposeful animations — spring physics, keyframe orchestration, enter/exit transitions, and gesture-driven interactions. Covers prefers-reduced-motion and performance.",
    capabilities: [
      "Spring and easing design",
      "Keyframe orchestration",
      "Enter and exit transitions",
      "Gesture-driven interactions",
      "Reduced motion accessibility",
      "FLIP animation technique",
    ],
    languages: ["TypeScript", "CSS"],
    frameworks: ["Motion One", "Framer Motion", "GSAP", "CSS Animations"],
    requiredConnectors: [],
    recommendedSkills: ["design-system", "accessibility"],
    version: "1.3.0",
    author: "SHANGO",
    category: "Design",
    featured: false,
    tags: ["animation", "motion", "transitions", "physics"],
    permissions: ["Read component files", "Modify animation definitions"],
    usageCount: 3710,
    health: "healthy",
    hasUpdate: false,
    updateHistory: [
      {
        version: "1.3.0",
        date: "2026-04-22",
        note: "View Transitions API support",
      },
    ],
  },
  // ── Database ──────────────────────────────────────────────────────────────
  {
    id: "database-postgres",
    name: "PostgreSQL",
    monogram: "Pg",
    purpose: "Relational database design, queries, and migrations",
    description:
      "SHANGO designs PostgreSQL schemas, writes optimised queries, and manages migrations. Covers indexes, CTEs, window functions, full-text search, and connection pooling with PgBouncer.",
    capabilities: [
      "Schema design and normalisation",
      "Query optimisation and explain plans",
      "Migrations with version control",
      "Full-text search",
      "Row-level security",
      "Connection pooling",
    ],
    languages: ["SQL", "TypeScript"],
    frameworks: ["PostgreSQL", "Prisma", "Drizzle", "pg-boss"],
    requiredConnectors: [],
    recommendedSkills: ["nodejs", "security"],
    version: "2.3.0",
    author: "SHANGO",
    category: "Database",
    featured: true,
    tags: ["sql", "relational", "migrations", "rls"],
    permissions: ["Read schema files", "Generate migration files"],
    usageCount: 9120,
    health: "healthy",
    hasUpdate: false,
    updateHistory: [
      {
        version: "2.3.0",
        date: "2026-06-08",
        note: "pg_vector native support",
      },
      {
        version: "2.2.0",
        date: "2026-03-01",
        note: "Row-level security patterns",
      },
    ],
  },
  {
    id: "database-redis",
    name: "Redis",
    monogram: "Rd",
    purpose: "In-memory caching, queues, and pub/sub messaging",
    description:
      "SHANGO architects Redis usage — caching layers, session storage, distributed locks, pub/sub messaging, and background job queues with BullMQ. Covers Redis Streams and cluster configuration.",
    capabilities: [
      "Caching strategy design",
      "Session and token storage",
      "Distributed locks",
      "Pub/sub messaging",
      "BullMQ job queues",
      "Redis Streams",
    ],
    languages: ["TypeScript", "Python"],
    frameworks: ["ioredis", "BullMQ", "Upstash", "Redis Stack"],
    requiredConnectors: [],
    recommendedSkills: ["nodejs", "database-postgres"],
    version: "1.5.0",
    author: "Community",
    category: "Database",
    featured: false,
    tags: ["cache", "queue", "pubsub", "in-memory"],
    permissions: ["Read project structure", "Read environment variables"],
    usageCount: 4360,
    health: "healthy",
    hasUpdate: false,
    updateHistory: [
      {
        version: "1.5.0",
        date: "2026-04-30",
        note: "Redis Stack JSON type support",
      },
    ],
  },
  // ── Security ──────────────────────────────────────────────────────────────
  {
    id: "security",
    name: "Security",
    monogram: "Se",
    purpose: "OWASP-aligned security patterns and threat modelling",
    description:
      "SHANGO applies security-first thinking — input validation, output encoding, CSRF protection, secure session management, and secrets handling. Covers OWASP Top 10 and dependency auditing.",
    capabilities: [
      "OWASP Top 10 mitigations",
      "Input validation and sanitisation",
      "JWT and session security",
      "CSRF and clickjacking protection",
      "Secrets management patterns",
      "Dependency vulnerability scanning",
    ],
    languages: ["TypeScript", "Python", "Go"],
    frameworks: ["Helmet.js", "OWASP ZAP", "Snyk", "Vault"],
    requiredConnectors: [],
    recommendedSkills: ["database-postgres", "cloud-aws"],
    version: "1.7.0",
    author: "SHANGO",
    category: "Security",
    featured: false,
    tags: ["owasp", "auth", "validation", "secrets"],
    permissions: ["Read project files", "Scan dependency manifests"],
    usageCount: 6840,
    health: "healthy",
    hasUpdate: true,
    updateVersion: "1.8.0",
    updateHistory: [
      {
        version: "1.7.0",
        date: "2026-05-18",
        note: "Supply chain security patterns",
      },
      {
        version: "1.6.0",
        date: "2026-02-25",
        note: "PKCE OAuth flow coverage",
      },
    ],
  },
  {
    id: "auth",
    name: "Authentication",
    monogram: "Au",
    purpose: "Complete auth flows — passwords, OAuth, passkeys",
    description:
      "SHANGO implements production authentication — email/password with bcrypt, OAuth 2.1 flows, PKCE, passkey (WebAuthn) registration, and secure session lifecycle management.",
    capabilities: [
      "Password hashing with bcrypt/argon2",
      "OAuth 2.1 with PKCE",
      "WebAuthn / Passkeys",
      "JWT and opaque sessions",
      "MFA and TOTP",
      "Account recovery flows",
    ],
    languages: ["TypeScript", "Python"],
    frameworks: ["Lucia Auth", "Auth.js", "Clerk", "Supabase Auth"],
    requiredConnectors: [],
    recommendedSkills: ["security", "database-postgres"],
    version: "2.0.0",
    author: "SHANGO",
    category: "Security",
    featured: true,
    tags: ["oauth", "jwt", "passkeys", "sessions"],
    permissions: [
      "Read project structure",
      "Generate auth files",
      "Read environment variables",
    ],
    usageCount: 8450,
    health: "healthy",
    hasUpdate: false,
    updateHistory: [
      {
        version: "2.0.0",
        date: "2026-06-12",
        note: "Passkey and WebAuthn full coverage",
      },
      {
        version: "1.9.0",
        date: "2026-03-08",
        note: "OAuth 2.1 with device flow",
      },
    ],
  },
  // ── DevOps ────────────────────────────────────────────────────────────────
  {
    id: "docker",
    name: "Docker",
    monogram: "Dk",
    purpose: "Containerise and orchestrate applications with Docker",
    description:
      "SHANGO creates optimised Dockerfiles, multi-stage builds, and Compose configurations. Covers layer caching, minimal base images, health checks, and secrets injection patterns.",
    capabilities: [
      "Multi-stage Dockerfile authoring",
      "Docker Compose orchestration",
      "Layer caching optimisation",
      "Health check configuration",
      "Secrets management",
      "Registry and CI integration",
    ],
    languages: ["YAML", "Dockerfile", "Shell"],
    frameworks: ["Docker", "Docker Compose", "Buildx"],
    requiredConnectors: [],
    recommendedSkills: ["cloud-aws", "testing"],
    version: "1.9.0",
    author: "SHANGO",
    category: "DevOps",
    featured: false,
    tags: ["containers", "ci", "build", "orchestration"],
    permissions: [
      "Read project structure",
      "Generate Dockerfile",
      "Modify CI config",
    ],
    usageCount: 7230,
    health: "healthy",
    hasUpdate: false,
    updateHistory: [
      {
        version: "1.9.0",
        date: "2026-05-25",
        note: "Bake and multi-platform support",
      },
    ],
  },
  {
    id: "cicd",
    name: "CI/CD",
    monogram: "CI",
    purpose: "Automated pipelines from commit to production",
    description:
      "SHANGO designs CI/CD pipelines — GitHub Actions workflows, matrix testing, dependency caching, environment promotion, canary deployments, and rollback strategies.",
    capabilities: [
      "GitHub Actions workflows",
      "Matrix and parallel testing",
      "Dependency caching strategies",
      "Environment promotion gating",
      "Canary and blue-green deploys",
      "Deployment rollback automation",
    ],
    languages: ["YAML", "Shell", "TypeScript"],
    frameworks: ["GitHub Actions", "CircleCI", "Cloudflare Workers CI"],
    requiredConnectors: [],
    recommendedSkills: ["docker", "testing", "cloud-aws"],
    version: "1.6.0",
    author: "SHANGO",
    category: "DevOps",
    featured: false,
    tags: ["pipeline", "automation", "github-actions", "deployment"],
    permissions: ["Read project structure", "Generate workflow files"],
    usageCount: 5890,
    health: "healthy",
    hasUpdate: false,
    updateHistory: [
      {
        version: "1.6.0",
        date: "2026-04-16",
        note: "Warp Speed cache action support",
      },
    ],
  },
  // ── Testing ───────────────────────────────────────────────────────────────
  {
    id: "testing",
    name: "Testing",
    monogram: "Te",
    purpose: "Unit, integration, and e2e testing with coverage",
    description:
      "SHANGO writes comprehensive test suites — unit tests with Vitest, integration tests with supertest, and end-to-end flows with Playwright. Covers test organisation, mocking strategies, and coverage targets.",
    capabilities: [
      "Unit tests with Vitest/Jest",
      "Integration test patterns",
      "E2E with Playwright",
      "Coverage reporting",
      "Test data factories",
      "CI integration",
    ],
    languages: ["TypeScript", "Python"],
    frameworks: ["Vitest", "Playwright", "Testing Library", "Jest"],
    requiredConnectors: [],
    recommendedSkills: ["react", "nodejs"],
    version: "2.1.0",
    author: "SHANGO",
    category: "Testing",
    featured: false,
    tags: ["unit", "e2e", "playwright", "vitest"],
    permissions: ["Read project structure", "Generate test files"],
    usageCount: 6710,
    health: "healthy",
    hasUpdate: false,
    updateHistory: [
      {
        version: "2.1.0",
        date: "2026-06-05",
        note: "Playwright Component Testing",
      },
      {
        version: "2.0.0",
        date: "2026-02-28",
        note: "Vitest 2.0 workspace support",
      },
    ],
  },
  // ── Performance ───────────────────────────────────────────────────────────
  {
    id: "performance",
    name: "Performance",
    monogram: "Pf",
    purpose: "Core Web Vitals optimisation and bundle analysis",
    description:
      "SHANGO optimises for Core Web Vitals — LCP, INP, CLS. Covers code splitting, tree shaking, image optimisation, font loading, lazy loading, and Lighthouse scoring strategies.",
    capabilities: [
      "Core Web Vitals (LCP, INP, CLS)",
      "Bundle analysis and tree shaking",
      "Code splitting strategies",
      "Image and font optimisation",
      "Lazy loading and prefetching",
      "Service worker caching",
    ],
    languages: ["TypeScript", "JavaScript"],
    frameworks: ["Lighthouse", "WebPageTest", "Partytown"],
    requiredConnectors: [],
    recommendedSkills: ["nextjs", "cloud-aws"],
    version: "1.5.0",
    author: "SHANGO",
    category: "Performance",
    featured: false,
    tags: ["cwv", "bundle", "lighthouse", "optimisation"],
    permissions: ["Read project structure", "Analyse bundle output"],
    usageCount: 4120,
    health: "healthy",
    hasUpdate: false,
    updateHistory: [
      {
        version: "1.5.0",
        date: "2026-05-12",
        note: "INP optimisation patterns",
      },
    ],
  },
  // ── Accessibility ─────────────────────────────────────────────────────────
  {
    id: "accessibility",
    name: "Accessibility",
    monogram: "A1",
    purpose: "WCAG 2.2 AA compliance and inclusive design",
    description:
      "SHANGO builds accessible interfaces from the ground up — semantic HTML, ARIA patterns, keyboard navigation, focus management, colour contrast, and screen reader compatibility.",
    capabilities: [
      "Semantic HTML and ARIA roles",
      "Keyboard navigation patterns",
      "Focus trap and management",
      "Colour contrast (WCAG 2.2 AA)",
      "Screen reader compatibility",
      "Reduced motion support",
    ],
    languages: ["TypeScript", "HTML", "CSS"],
    frameworks: ["Radix UI", "Headless UI", "axe-core"],
    requiredConnectors: [],
    recommendedSkills: ["design-system", "testing"],
    version: "1.8.0",
    author: "SHANGO",
    category: "Accessibility",
    featured: false,
    tags: ["wcag", "aria", "a11y", "keyboard", "screen-reader"],
    permissions: ["Read component files", "Generate accessible markup"],
    usageCount: 3480,
    health: "healthy",
    hasUpdate: false,
    updateHistory: [
      {
        version: "1.8.0",
        date: "2026-06-18",
        note: "WCAG 2.2 new criteria support",
      },
      {
        version: "1.7.0",
        date: "2026-03-30",
        note: "ARIA 1.2 pattern library",
      },
    ],
  },
  // ── Cloud ─────────────────────────────────────────────────────────────────
  {
    id: "cloud-aws",
    name: "AWS",
    monogram: "AW",
    purpose: "Infrastructure design and deployment on AWS",
    description:
      "SHANGO architects AWS infrastructure — CDK stacks, Lambda functions, S3/CloudFront, RDS, ECS, and IAM least-privilege policies. Covers cost optimisation and multi-region patterns.",
    capabilities: [
      "CDK infrastructure as code",
      "Lambda and serverless patterns",
      "S3 and CloudFront delivery",
      "RDS and Aurora Serverless",
      "ECS and Fargate deployments",
      "IAM least-privilege design",
    ],
    languages: ["TypeScript", "Python", "YAML"],
    frameworks: ["AWS CDK", "Serverless Framework", "SAM"],
    requiredConnectors: ["AWS"],
    recommendedSkills: ["docker", "database-postgres", "security"],
    version: "2.0.0",
    author: "SHANGO",
    category: "Cloud",
    featured: false,
    tags: ["lambda", "cdk", "s3", "serverless"],
    permissions: [
      "Read project structure",
      "Read cloud config files",
      "Generate CDK stacks",
    ],
    usageCount: 7540,
    health: "healthy",
    hasUpdate: true,
    updateVersion: "2.1.0",
    updateHistory: [
      {
        version: "2.0.0",
        date: "2026-05-22",
        note: "AWS Bedrock integration patterns",
      },
      { version: "1.9.0", date: "2026-02-10", note: "CDK v2 migration guide" },
    ],
  },
  {
    id: "cloud-cloudflare",
    name: "Cloudflare",
    monogram: "CF",
    purpose: "Edge compute, Workers, and global delivery",
    description:
      "SHANGO builds on Cloudflare's edge platform — Workers, Durable Objects, R2 storage, D1 database, KV, and Pages. Covers edge-first architecture and geo-aware routing.",
    capabilities: [
      "Workers and edge functions",
      "Durable Objects patterns",
      "R2 object storage",
      "D1 SQLite database",
      "KV key-value store",
      "Pages and edge SSR",
    ],
    languages: ["TypeScript", "JavaScript"],
    frameworks: ["Hono", "Cloudflare Workers SDK", "Wrangler"],
    requiredConnectors: ["Cloudflare"],
    recommendedSkills: ["nodejs", "performance"],
    version: "1.4.0",
    author: "Community",
    category: "Cloud",
    featured: false,
    tags: ["edge", "workers", "cdn", "durable-objects"],
    permissions: ["Read project structure", "Read wrangler config"],
    usageCount: 3270,
    health: "healthy",
    hasUpdate: false,
    updateHistory: [
      {
        version: "1.4.0",
        date: "2026-06-14",
        note: "Workflows and AI Gateway support",
      },
    ],
  },
  // ── Automation ────────────────────────────────────────────────────────────
  {
    id: "automation",
    name: "Automation",
    monogram: "At",
    purpose: "Script and automate repetitive workflows",
    description:
      "SHANGO creates automation scripts — scheduled jobs, file processing pipelines, webhook handlers, and workflow orchestration. Covers cron scheduling, retry logic, and observability.",
    capabilities: [
      "Cron scheduling patterns",
      "Webhook ingestion pipelines",
      "File processing workflows",
      "Retry and backoff strategies",
      "Observability and alerting",
      "Workflow state machines",
    ],
    languages: ["TypeScript", "Python", "Shell"],
    frameworks: ["Temporal", "BullMQ", "Inngest", "n8n"],
    requiredConnectors: [],
    recommendedSkills: ["nodejs", "database-redis"],
    version: "1.3.0",
    author: "SHANGO",
    category: "Automation",
    featured: false,
    tags: ["cron", "workflows", "queues", "pipelines"],
    permissions: ["Read project structure", "Generate workflow files"],
    usageCount: 2840,
    health: "healthy",
    hasUpdate: false,
    updateHistory: [
      { version: "1.3.0", date: "2026-04-28", note: "Temporal saga patterns" },
    ],
  },
  // ── Integrations ──────────────────────────────────────────────────────────
  {
    id: "integrations-stripe",
    name: "Stripe",
    monogram: "St",
    purpose: "Payment processing, subscriptions, and billing",
    description:
      "SHANGO implements Stripe integrations — payment intent flows, subscription billing, webhook handling, and customer portal. Covers SCA compliance and idempotency best practices.",
    capabilities: [
      "Payment intent flows",
      "Subscription and billing cycles",
      "Webhook event handling",
      "Customer portal integration",
      "SCA and 3DS2 compliance",
      "Refund and dispute handling",
    ],
    languages: ["TypeScript", "Python"],
    frameworks: ["Stripe SDK", "Stripe Elements"],
    requiredConnectors: ["Stripe"],
    recommendedSkills: ["nodejs", "security", "database-postgres"],
    version: "1.7.0",
    author: "Community",
    category: "Integrations",
    featured: false,
    tags: ["payments", "subscriptions", "billing", "webhooks"],
    permissions: [
      "Read project structure",
      "Read environment variables",
      "Access Stripe connector",
    ],
    usageCount: 5630,
    health: "healthy",
    hasUpdate: false,
    updateHistory: [
      {
        version: "1.7.0",
        date: "2026-06-02",
        note: "Stripe Sessions v2 support",
      },
    ],
  },
  {
    id: "integrations-supabase",
    name: "Supabase",
    monogram: "Sb",
    purpose: "Open-source Firebase alternative with Postgres",
    description:
      "SHANGO integrates Supabase — Auth, Realtime, Edge Functions, Row Level Security, and Storage. Covers the Supabase client SDK and server-side patterns with service role keys.",
    capabilities: [
      "Supabase Auth integration",
      "Realtime subscriptions",
      "Row Level Security policies",
      "Edge Functions",
      "Storage bucket management",
      "Supabase CLI and migrations",
    ],
    languages: ["TypeScript", "SQL"],
    frameworks: ["Supabase JS SDK", "Supabase CLI"],
    requiredConnectors: ["Supabase"],
    recommendedSkills: ["database-postgres", "auth", "react"],
    version: "2.1.0",
    author: "SHANGO",
    category: "Integrations",
    featured: true,
    tags: ["backend-as-service", "realtime", "rls", "storage"],
    permissions: [
      "Read project structure",
      "Access Supabase connector",
      "Read environment variables",
    ],
    usageCount: 6920,
    health: "healthy",
    hasUpdate: false,
    updateHistory: [
      {
        version: "2.1.0",
        date: "2026-06-22",
        note: "Supabase AI and pgvector helpers",
      },
      {
        version: "2.0.0",
        date: "2026-03-14",
        note: "Edge Functions v2 support",
      },
    ],
  },
  // ── Documentation ─────────────────────────────────────────────────────────
  {
    id: "docs",
    name: "Documentation",
    monogram: "Do",
    purpose: "Auto-generate docs, READMEs, and API references",
    description:
      "SHANGO writes documentation alongside code — README files, JSDoc/TSDoc annotations, OpenAPI specs, architecture decision records, and changelog entries. Everything stays in sync.",
    capabilities: [
      "README and getting-started guides",
      "JSDoc and TSDoc annotations",
      "OpenAPI 3.1 spec generation",
      "Architecture Decision Records",
      "Changelog and release notes",
      "Docusaurus site scaffolding",
    ],
    languages: ["Markdown", "TypeScript", "YAML"],
    frameworks: ["Docusaurus", "TypeDoc", "Swagger UI", "Mintlify"],
    requiredConnectors: [],
    recommendedSkills: ["nodejs", "testing"],
    version: "1.4.0",
    author: "SHANGO",
    category: "Documentation",
    featured: false,
    tags: ["readme", "openapi", "tsdoc", "changelog"],
    permissions: ["Read all project files", "Generate markdown files"],
    usageCount: 4180,
    health: "healthy",
    hasUpdate: false,
    updateHistory: [
      {
        version: "1.4.0",
        date: "2026-05-08",
        note: "Mintlify and Scalar support",
      },
    ],
  },
]

// Default installed skills (pre-seeded for new accounts)
export const DEFAULT_INSTALLED_SKILL_IDS = [
  "react",
  "typescript",
  "tailwind",
  "nodejs",
  "database-postgres",
  "auth",
]
export const DEFAULT_ENABLED_SKILL_IDS = ["react", "typescript", "tailwind"]

export const SKILL_CATEGORIES: SkillCategory[] = [
  "Frontend",
  "Backend",
  "Mobile",
  "AI",
  "Design",
  "Database",
  "Security",
  "DevOps",
  "Testing",
  "Performance",
  "Accessibility",
  "Cloud",
  "Automation",
  "Integrations",
  "Documentation",
]

export function getSkillById(id: string): Skill | undefined {
  return ALL_SKILLS.find((s) => s.id === id)
}

export function getSkillsByCategory(category: SkillCategory): Skill[] {
  return ALL_SKILLS.filter((s) => s.category === category)
}

export function getFeaturedSkills(): Skill[] {
  return ALL_SKILLS.filter((s) => s.featured)
}

export function searchSkills(query: string): Skill[] {
  const q = query.toLowerCase()
  return ALL_SKILLS.filter(
    (s) =>
      s.name.toLowerCase().includes(q) ||
      s.purpose.toLowerCase().includes(q) ||
      s.tags.some((t) => t.includes(q)) ||
      s.languages.some((l) => l.toLowerCase().includes(q)) ||
      s.frameworks.some((f) => f.toLowerCase().includes(q)),
  )
}
